name: Build and run tests

on:
  push:
    # branches:
    #   - develop
  pull_request:
    branches:
      - develop

jobs:
  backend-node:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git auth
        run: git config --global url."https://token:$PAT@github.com/iotaledger/actors.rs".insteadOf "https://github.com/iotaledger/actors.rs"
        env:
          PAT: ${{ secrets.PAT }}

      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install Rust dependencies
        run: cargo build
        working-directory: backend
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true

      - name: Build Node.js bindings
        run: yarn
        working-directory: backend/bindings/node

      - name: Run tests
        run: yarn test
        working-directory: backend/bindings/node
        
      
  frontend-desktop:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git auth
      run: |
        git config --global url."https://token:$PAT@github.com/iotaledger/actors.rs".insteadOf "https://github.com/iotaledger/actors.rs"
      env:
        PAT: ${{ secrets.PAT }}

    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
      
    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install gcc-multilib g++-multilib build-essential

    - name: Install backend dependencies
      run: cargo build
      working-directory: backend
      env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
    
    - name: Install shared frontend dependencies
      run: yarn
      working-directory: frontend/src/shared
    
    - name: Install desktop frontend dependencies
      run: yarn
      working-directory: frontend/src/desktop
      
    - name: Bundle desktop JS
      run: yarn build
      working-directory: frontend/src/desktop
